name: easyshare
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  qr_flutter: ^3.2.0
  qrscan: ^0.2.17
  file_picker: ^1.9.0+1
  url_launcher: ^5.4.5
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
        - asset: fonts/NotoSans-BoldItalic.ttf
        - asset: fonts/NotoSans-Italic.ttf
        - asset: fonts/NotoSans-Regular.ttf
  assets:
    - assets/